name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-west-2 | \
        docker login --username AWS --password-stdin 187249972779.dkr.ecr.us-west-2.amazonaws.com

    - name: Build and Push Docker Image
      run: |
        docker buildx build -t httpd-image:latest .
        docker tag httpd-image:latest 187249972779.dkr.ecr.us-west-2.amazonaws.com/venkat:latest
        docker push 187249972779.dkr.ecr.us-west-2.amazonaws.com/venkat:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-west-2 --name httpd-eks-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/deployment.yaml
